version: '2.0'

services:
    # redis:
    #     image: redis:alpine
    #     ports:
    #         - "127.0.0.1:16379:6379"
    mysql:
        image: mariadb
        ports:
            - "127.0.0.1:13306:3306"
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            # MySQL isn't publicly visible, there's no real need to be very
            # secure about these passwords
            MYSQL_ROOT_PASSWORD: zuqu5oowi0kei8Mui3xieph5ahn8shah
            MYSQL_USER: idp_usr
            MYSQL_PASSWORD: mai9olaughaisau9TaineeDohGhah0eX
            MYSQL_DATABASE: idp_db
