version: '2.0'

services:
    redis:
        image: redis:4-alpine
        ports:
            - "127.0.0.1:16379:6379"
    mysql:
        image: mariadb:10.1
        ports:
            - "127.0.0.1:13306:3306"
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            # MySQL isn't publicly visible, there's no real need to be very
            # secure about these passwords
            MYSQL_ROOT_PASSWORD: dFIjpkZIlH9QJAc8gHHmfoHbWcfIrlYALAzbhY47
            MYSQL_USER: idp_user
            MYSQL_PASSWORD: H25EN7giIxLcnDOatNTd154AZocltXfNvO4qSSlH
            MYSQL_DATABASE: idp_app
